# Keys for LocalizationManger to use in source code: MIT License
# @author Vladimir Petrenko
@tool
class_name LocalizationKeys

const TEST = "TEST"
const YES = "YES"
const NO = "NO"
const EXIT_BUTTON = "EXIT_BUTTON"
const PROFILE_TOOLTIP = "PROFILE_TOOLTIP"
const PLAY_BUTTON = "PLAY_BUTTON"
const PLAY_TOOLTIP = "PLAY_TOOLTIP"
const SPLASH_LOADING = "SPLASH_LOADING"
const CHANGE_PROFILE_BUTTON = "CHANGE_PROFILE_BUTTON"
const LEVEL_EDITOR_BUTTON = "LEVEL_EDITOR_BUTTON"
const LEVEL_EDITOR_TOOLTIP = "LEVEL_EDITOR_TOOLTIP"
const EXIT_CONFIRMATION = "EXIT_CONFIRMATION"
const DEFAULT_CONFIRMATION = "DEFAULT_CONFIRMATION"
const WATERS_COUNTER = "WATERS_COUNTER"
const WATERS_COUNTER_EDITOR = "WATERS_COUNTER_EDITOR"
const BOATS_COUNTER = "BOATS_COUNTER"
const BOATS_COUNTER_EDITOR = "BOATS_COUNTER_EDITOR"
const MISTAKES_COUNTER = "MISTAKES_COUNTER"
const MASTER_SOUND = "MASTER_SOUND"
const BGM_SOUND = "BGM_SOUND"
const SFX_SOUND = "SFX_SOUND"
const FULLSCREEN = "FULLSCREEN"
const SAVE_AND_EXIT = "SAVE_AND_EXIT"
const SAVE_AND_BACK = "SAVE_AND_BACK"
const REMOVE_ADS = "REMOVE_ADS"
const AQUARIUMS_COUNTER = "AQUARIUMS_COUNTER"
const AQUARIUMS_COUNTER_EDITOR = "AQUARIUMS_COUNTER_EDITOR"
const SIZE = "SIZE"
const AQ_AMOUNT = "AQ_AMOUNT"
const AQ_AMOUNT_EDITOR = "AQ_AMOUNT_EDITOR"
const BACK = "BACK"
const CONTINUE = "CONTINUE"
const CREATE_NEW_LEVEL = "CREATE_NEW_LEVEL"
const YOUR_LEVELS = "YOUR_LEVELS"
const PROFILE = "PROFILE"
const CHANGE_PROFILE = "CHANGE_PROFILE"
const CONFIRM_DELETE_PROFILE = "CONFIRM_DELETE_PROFILE"
const CONFIRM_RESET_LEVEL = "CONFIRM_RESET_LEVEL"
const CONFIRM_RESET_DAILY = "CONFIRM_RESET_DAILY"
const LEVELS_COMPLETED = "LEVELS_COMPLETED"
const WORKSHOP_BUTTON = "WORKSHOP_BUTTON"
const WORKSHOP_TOOLTIP = "WORKSHOP_TOOLTIP"
const WORKSHOP_LEVELS = "WORKSHOP_LEVELS"
const PLAY_LEVEL_TOOLTIP = "PLAY_LEVEL_TOOLTIP"
const EDIT_LEVEL_TOOLTIP = "EDIT_LEVEL_TOOLTIP"
const UPLOAD_LEVEL_TOOLTIP = "UPLOAD_LEVEL_TOOLTIP"
const DELETE_LEVEL_TOOLTIP = "DELETE_LEVEL_TOOLTIP"
const NOT_INSTALLED = "NOT_INSTALLED"
const COMPLETED_LEVEL = "COMPLETED_LEVEL"
const NOT_COMPLETED_LEVEL = "NOT_COMPLETED_LEVEL"
const BEST_TIME = "BEST_TIME"
const BEST_MISTAKES = "BEST_MISTAKES"
const RANDOM_BUTTON = "RANDOM_BUTTON"
const RANDOM_TOOLTIP = "RANDOM_TOOLTIP"
const RANDOM_TITLE = "RANDOM_TITLE"
const EASY_BUTTON = "EASY_BUTTON"
const MEDIUM_BUTTON = "MEDIUM_BUTTON"
const HARD_BUTTON = "HARD_BUTTON"
const EXPERT_BUTTON = "EXPERT_BUTTON"
const INSANE_BUTTON = "INSANE_BUTTON"
const RANDOM_COMPLETED = "RANDOM_COMPLETED"
const CONFIRM_NEW_RANDOM = "CONFIRM_NEW_RANDOM"
const FIRST_LEVEL_DESCRIPTION = "FIRST_LEVEL_DESCRIPTION"
const SECOND_LEVEL_DESCRIPTION = "SECOND_LEVEL_DESCRIPTION"
const THIRD_LEVEL_DESCRIPTION = "THIRD_LEVEL_DESCRIPTION"
const UNIQUE_SOLUTION_DESCRIPTION = "UNIQUE_SOLUTION_DESCRIPTION"
const PLAYTEST = "PLAYTEST"
const LEVEL_DESCRIPTION_PLACEHOLDER = "LEVEL_DESCRIPTION_PLACEHOLDER"
const LEVEL_TITLE_PLACEHOLDER = "LEVEL_TITLE_PLACEHOLDER"
const EASY_TOOLTIP = "EASY_TOOLTIP"
const MEDIUM_TOOLTIP = "MEDIUM_TOOLTIP"
const MEDIUM_TOOLTIP_DISABLED = "MEDIUM_TOOLTIP_DISABLED"
const HARD_TOOLTIP = "HARD_TOOLTIP"
const HARD_TOOLTIP_DISABLED = "HARD_TOOLTIP_DISABLED"
const EXPERT_TOOLTIP = "EXPERT_TOOLTIP"
const EXPERT_TOOLTIP_DISABLED = "EXPERT_TOOLTIP_DISABLED"
const INSANE_TOOLTIP = "INSANE_TOOLTIP"
const INSANE_TOOLTIP_DISABLED = "INSANE_TOOLTIP_DISABLED"
const GENERATING_LEVEL = "GENERATING_LEVEL"
const LEVEL_01_01 = "LEVEL_01_01"
const LEVEL_01_02 = "LEVEL_01_02"
const LEVEL_01_03 = "LEVEL_01_03"
const LEVEL_01_04 = "LEVEL_01_04"
const LEVEL_01_05 = "LEVEL_01_05"
const LEVEL_01_06 = "LEVEL_01_06"
const LEVEL_01_07 = "LEVEL_01_07"
const LEVEL_01_08 = "LEVEL_01_08"
const LEVEL_02_01 = "LEVEL_02_01"
const LEVEL_02_02 = "LEVEL_02_02"
const LEVEL_02_03 = "LEVEL_02_03"
const LEVEL_02_04 = "LEVEL_02_04"
const LEVEL_02_05 = "LEVEL_02_05"
const LEVEL_02_06 = "LEVEL_02_06"
const LEVEL_02_07 = "LEVEL_02_07"
const LEVEL_02_08 = "LEVEL_02_08"
const LEVEL_03_01 = "LEVEL_03_01"
const LEVEL_03_02 = "LEVEL_03_02"
const LEVEL_03_03 = "LEVEL_03_03"
const LEVEL_03_04 = "LEVEL_03_04"
const LEVEL_03_05 = "LEVEL_03_05"
const LEVEL_03_06 = "LEVEL_03_06"
const LEVEL_03_07 = "LEVEL_03_07"
const LEVEL_03_08 = "LEVEL_03_08"
const LEVEL_04_01 = "LEVEL_04_01"
const LEVEL_04_02 = "LEVEL_04_02"
const LEVEL_04_03 = "LEVEL_04_03"
const LEVEL_04_04 = "LEVEL_04_04"
const LEVEL_04_05 = "LEVEL_04_05"
const LEVEL_04_06 = "LEVEL_04_06"
const LEVEL_04_07 = "LEVEL_04_07"
const LEVEL_04_08 = "LEVEL_04_08"
const LEVEL_05_01 = "LEVEL_05_01"
const LEVEL_05_02 = "LEVEL_05_02"
const LEVEL_05_03 = "LEVEL_05_03"
const LEVEL_05_04 = "LEVEL_05_04"
const LEVEL_05_05 = "LEVEL_05_05"
const LEVEL_05_06 = "LEVEL_05_06"
const LEVEL_05_07 = "LEVEL_05_07"
const LEVEL_05_08 = "LEVEL_05_08"
const LEVEL_06_01 = "LEVEL_06_01"
const LEVEL_06_02 = "LEVEL_06_02"
const LEVEL_06_03 = "LEVEL_06_03"
const LEVEL_06_04 = "LEVEL_06_04"
const LEVEL_06_05 = "LEVEL_06_05"
const LEVEL_06_06 = "LEVEL_06_06"
const LEVEL_06_07 = "LEVEL_06_07"
const LEVEL_06_08 = "LEVEL_06_08"
const DAILY_BUTTON = "DAILY_BUTTON"
const DAILY_LEVEL_NOT_PLAYED_TOOLTIP = "DAILY_LEVEL_NOT_PLAYED_TOOLTIP"
const DAILY_LEVEL_PLAYED_TOOLTIP = "DAILY_LEVEL_PLAYED_TOOLTIP"
const DAILY_TOOLTIP = "DAILY_TOOLTIP"
const DAILY_TOOLTIP_DISABLED = "DAILY_TOOLTIP_DISABLED"
const CUR_STREAK = "CUR_STREAK"
const BEST_STREAK = "BEST_STREAK"
const STREAK_TOOLTIP = "STREAK_TOOLTIP"
const HOURS_LEFT = "HOURS_LEFT"
const MINUTES_LEFT = "MINUTES_LEFT"
const MONDAY_LEVEL = "MONDAY_LEVEL"
const MONDAY_LEVEL_DESC = "MONDAY_LEVEL_DESC"
const TUESDAY_LEVEL = "TUESDAY_LEVEL"
const TUESDAY_LEVEL_DESC = "TUESDAY_LEVEL_DESC"
const WEDNESDAY_LEVEL = "WEDNESDAY_LEVEL"
const WEDNESDAY_LEVEL_DESC = "WEDNESDAY_LEVEL_DESC"
const THURSDAY_LEVEL = "THURSDAY_LEVEL"
const THURSDAY_LEVEL_DESC = "THURSDAY_LEVEL_DESC"
const FRIDAY_LEVEL = "FRIDAY_LEVEL"
const FRIDAY_LEVEL_DESC = "FRIDAY_LEVEL_DESC"
const SATURDAY_LEVEL = "SATURDAY_LEVEL"
const SATURDAY_LEVEL_DESC = "SATURDAY_LEVEL_DESC"
const SUNDAY_LEVEL = "SUNDAY_LEVEL"
const SUNDAY_LEVEL_DESC = "SUNDAY_LEVEL_DESC"
const UPLOADING_TO_WORKSHOP = "UPLOADING_TO_WORKSHOP"
const PCT_1 = "PCT_1"
const PCT_10 = "PCT_10"
const PCT_50 = "PCT_50"
const HARD_LEVEL_TOOLTIP = "HARD_LEVEL_TOOLTIP"
const USE_CUSTOM_SEED = "USE_CUSTOM_SEED"
const SEED = "SEED"
const DARK_MODE = "DARK_MODE"
const HIGHLIGHT_LINES = "HIGHLIGHT_LINES"
const SHOW_PREVIEW = "SHOW_PREVIEW"
const DRAG_BUTTON = "DRAG_BUTTON"
const INCOMPLETE_LINE_INFO = "INCOMPLETE_LINE_INFO"
const LINE_INFO_NONE = "LINE_INFO_NONE"
const LINE_INFO_MISSING = "LINE_INFO_MISSING"
const LINE_INFO_CURRENT = "LINE_INFO_CURRENT"
const LANGUAGE_SELECT = "LANGUAGE_SELECT"
const LANGUAGE_SYSTEM = "LANGUAGE_SYSTEM"
const INVERT_MOUSE = "INVERT_MOUSE"
const SOUND = "SOUND"
const DISPLAY = "DISPLAY"
const GAMEPLAY = "GAMEPLAY"
const CONTROLS = "CONTROLS"
const CREDITS_BUTTON = "CREDITS_BUTTON"
const MADE_BY = "MADE_BY"
const MADE_USING = "MADE_USING"
const COMPANY = "COMPANY"
const OUR_OTHER_GAMES = "OUR_OTHER_GAMES"
const SPECIAL_THANKS_TITLE = "SPECIAL_THANKS_TITLE"
const SPECIAL_THANKS = "SPECIAL_THANKS"
const THANK_YOU_FOR_PLAYING = "THANK_YOU_FOR_PLAYING"
const FINISHED_ALL_LEVELS = "FINISHED_ALL_LEVELS"
const WIN_100_TIMES = "WIN_100_TIMES"
const EMAIL_US = "EMAIL_US"
const RESTART_MAY_BE_NECESSARY = "RESTART_MAY_BE_NECESSARY"
const HAS_UNIQUE = "HAS_UNIQUE"
const UNKNOWN = "UNKNOWN"
const UNIQUE_TOO_HARD = "UNIQUE_TOO_HARD"
const CHECK = "CHECK"
const CANCEL = "CANCEL"
const AGO = "AGO"
const LAST_SAVED = "LAST_SAVED"
const SHARE = "SHARE"
const COPIED_TO_CLIPBOARD = "COPIED_TO_CLIPBOARD"
const SHARE_TEXT = "SHARE_TEXT"
const LEFT_MOUSE_CLICK = "LEFT_MOUSE_CLICK"
const PLACE_BRUSH = "PLACE_BRUSH"
const RIGHT_MOUSE_CLICK = "RIGHT_MOUSE_CLICK"
const PLACE_X = "PLACE_X"
const MOUSE_DRAG = "MOUSE_DRAG"
const PLACE_DRAG = "PLACE_DRAG"
const NUMBER_KEYS = "NUMBER_KEYS"
const NUMBER_CONTROLS = "NUMBER_CONTROLS"
const TAB = "TAB"
const NEXT_BRUSH = "NEXT_BRUSH"
const SHIFT_TAB = "SHIFT_TAB"
const PREV_BRUSH = "PREV_BRUSH"
const ESC = "ESC"
const SETTINGS_CONTROL = "SETTINGS_CONTROL"
const PLACE_WATER = "PLACE_WATER"
const PLACE_NOWATER = "PLACE_NOWATER"
const PLACE_BOAT = "PLACE_BOAT"
const PLACE_NOBOAT = "PLACE_NOBOAT"
const UNDO = "UNDO"
const REDO = "REDO"
const TAP = "TAP"
const HOLD = "HOLD"
const DRAG_TOUCH = "DRAG_TOUCH"
const CONTROL_LIST = "CONTROL_LIST"
const PREVIEW = "PREVIEW"
const MOUSE_HOVER = "MOUSE_HOVER"
const LEADERBOARDS = "LEADERBOARDS"
const MISTAKE = "MISTAKE"
const MISTAKES = "MISTAKES"
const VSYNC = "VSYNC"
const DISABLED = "DISABLED"
const ENABLED = "ENABLED"
const ADAPTATIVE = "ADAPTATIVE"
const MAILBOX = "MAILBOX"
const TUT_BOATS = "TUT_BOATS"
const TUT_MOUSE1 = "TUT_MOUSE1"
const TUT_MOUSE2 = "TUT_MOUSE2"
const TUT_TOG_SEP = "TUT_TOG_SEP"
const TUT_UNKNOWN = "TUT_UNKNOWN"
const OPEN_WORKSHOP = "OPEN_WORKSHOP"
const TODAY = "TODAY"
const YESTERDAY = "YESTERDAY"
const SHOW_TIMER = "SHOW_TIMER"
const QUITTING = "QUITTING"
const ALLOW_MISTAKES = "ALLOW_MISTAKES"
const PROGRESS_ON_UNKNOWN = "PROGRESS_ON_UNKNOWN"
const LESS_THREE_MISTAKES = "LESS_THREE_MISTAKES"
const PREVIEW_TUT = "PREVIEW_TUT"
const TUT_PREVIEW = "TUT_PREVIEW"
const HOVER = "HOVER"
const SHOW_BUBBLES = "SHOW_BUBBLES"
const EXTRA_LEVELS_BUTTON = "EXTRA_LEVELS_BUTTON"

const KEYS = [
 "TEST",
 "YES",
 "NO",
 "EXIT_BUTTON",
 "PROFILE_TOOLTIP",
 "PLAY_BUTTON",
 "PLAY_TOOLTIP",
 "SPLASH_LOADING",
 "CHANGE_PROFILE_BUTTON",
 "LEVEL_EDITOR_BUTTON",
 "LEVEL_EDITOR_TOOLTIP",
 "EXIT_CONFIRMATION",
 "DEFAULT_CONFIRMATION",
 "WATERS_COUNTER",
 "WATERS_COUNTER_EDITOR",
 "BOATS_COUNTER",
 "BOATS_COUNTER_EDITOR",
 "MISTAKES_COUNTER",
 "MASTER_SOUND",
 "BGM_SOUND",
 "SFX_SOUND",
 "FULLSCREEN",
 "SAVE_AND_EXIT",
 "SAVE_AND_BACK",
 "REMOVE_ADS",
 "AQUARIUMS_COUNTER",
 "AQUARIUMS_COUNTER_EDITOR",
 "SIZE",
 "AQ_AMOUNT",
 "AQ_AMOUNT_EDITOR",
 "BACK",
 "CONTINUE",
 "CREATE_NEW_LEVEL",
 "YOUR_LEVELS",
 "PROFILE",
 "CHANGE_PROFILE",
 "CONFIRM_DELETE_PROFILE",
 "CONFIRM_RESET_LEVEL",
 "CONFIRM_RESET_DAILY",
 "LEVELS_COMPLETED",
 "WORKSHOP_BUTTON",
 "WORKSHOP_TOOLTIP",
 "WORKSHOP_LEVELS",
 "PLAY_LEVEL_TOOLTIP",
 "EDIT_LEVEL_TOOLTIP",
 "UPLOAD_LEVEL_TOOLTIP",
 "DELETE_LEVEL_TOOLTIP",
 "NOT_INSTALLED",
 "COMPLETED_LEVEL",
 "NOT_COMPLETED_LEVEL",
 "BEST_TIME",
 "BEST_MISTAKES",
 "RANDOM_BUTTON",
 "RANDOM_TOOLTIP",
 "RANDOM_TITLE",
 "EASY_BUTTON",
 "MEDIUM_BUTTON",
 "HARD_BUTTON",
 "EXPERT_BUTTON",
 "INSANE_BUTTON",
 "RANDOM_COMPLETED",
 "CONFIRM_NEW_RANDOM",
 "FIRST_LEVEL_DESCRIPTION",
 "SECOND_LEVEL_DESCRIPTION",
 "THIRD_LEVEL_DESCRIPTION",
 "UNIQUE_SOLUTION_DESCRIPTION",
 "PLAYTEST",
 "LEVEL_DESCRIPTION_PLACEHOLDER",
 "LEVEL_TITLE_PLACEHOLDER",
 "EASY_TOOLTIP",
 "MEDIUM_TOOLTIP",
 "MEDIUM_TOOLTIP_DISABLED",
 "HARD_TOOLTIP",
 "HARD_TOOLTIP_DISABLED",
 "EXPERT_TOOLTIP",
 "EXPERT_TOOLTIP_DISABLED",
 "INSANE_TOOLTIP",
 "INSANE_TOOLTIP_DISABLED",
 "GENERATING_LEVEL",
 "LEVEL_01_01",
 "LEVEL_01_02",
 "LEVEL_01_03",
 "LEVEL_01_04",
 "LEVEL_01_05",
 "LEVEL_01_06",
 "LEVEL_01_07",
 "LEVEL_01_08",
 "LEVEL_02_01",
 "LEVEL_02_02",
 "LEVEL_02_03",
 "LEVEL_02_04",
 "LEVEL_02_05",
 "LEVEL_02_06",
 "LEVEL_02_07",
 "LEVEL_02_08",
 "LEVEL_03_01",
 "LEVEL_03_02",
 "LEVEL_03_03",
 "LEVEL_03_04",
 "LEVEL_03_05",
 "LEVEL_03_06",
 "LEVEL_03_07",
 "LEVEL_03_08",
 "LEVEL_04_01",
 "LEVEL_04_02",
 "LEVEL_04_03",
 "LEVEL_04_04",
 "LEVEL_04_05",
 "LEVEL_04_06",
 "LEVEL_04_07",
 "LEVEL_04_08",
 "LEVEL_05_01",
 "LEVEL_05_02",
 "LEVEL_05_03",
 "LEVEL_05_04",
 "LEVEL_05_05",
 "LEVEL_05_06",
 "LEVEL_05_07",
 "LEVEL_05_08",
 "LEVEL_06_01",
 "LEVEL_06_02",
 "LEVEL_06_03",
 "LEVEL_06_04",
 "LEVEL_06_05",
 "LEVEL_06_06",
 "LEVEL_06_07",
 "LEVEL_06_08",
 "DAILY_BUTTON",
 "DAILY_LEVEL_NOT_PLAYED_TOOLTIP",
 "DAILY_LEVEL_PLAYED_TOOLTIP",
 "DAILY_TOOLTIP",
 "DAILY_TOOLTIP_DISABLED",
 "CUR_STREAK",
 "BEST_STREAK",
 "STREAK_TOOLTIP",
 "HOURS_LEFT",
 "MINUTES_LEFT",
 "MONDAY_LEVEL",
 "MONDAY_LEVEL_DESC",
 "TUESDAY_LEVEL",
 "TUESDAY_LEVEL_DESC",
 "WEDNESDAY_LEVEL",
 "WEDNESDAY_LEVEL_DESC",
 "THURSDAY_LEVEL",
 "THURSDAY_LEVEL_DESC",
 "FRIDAY_LEVEL",
 "FRIDAY_LEVEL_DESC",
 "SATURDAY_LEVEL",
 "SATURDAY_LEVEL_DESC",
 "SUNDAY_LEVEL",
 "SUNDAY_LEVEL_DESC",
 "UPLOADING_TO_WORKSHOP",
 "PCT_1",
 "PCT_10",
 "PCT_50",
 "HARD_LEVEL_TOOLTIP",
 "USE_CUSTOM_SEED",
 "SEED",
 "DARK_MODE",
 "HIGHLIGHT_LINES",
 "SHOW_PREVIEW",
 "DRAG_BUTTON",
 "INCOMPLETE_LINE_INFO",
 "LINE_INFO_NONE",
 "LINE_INFO_MISSING",
 "LINE_INFO_CURRENT",
 "LANGUAGE_SELECT",
 "LANGUAGE_SYSTEM",
 "INVERT_MOUSE",
 "SOUND",
 "DISPLAY",
 "GAMEPLAY",
 "CONTROLS",
 "CREDITS_BUTTON",
 "MADE_BY",
 "MADE_USING",
 "COMPANY",
 "OUR_OTHER_GAMES",
 "SPECIAL_THANKS_TITLE",
 "SPECIAL_THANKS",
 "THANK_YOU_FOR_PLAYING",
 "FINISHED_ALL_LEVELS",
 "WIN_100_TIMES",
 "EMAIL_US",
 "RESTART_MAY_BE_NECESSARY",
 "HAS_UNIQUE",
 "UNKNOWN",
 "UNIQUE_TOO_HARD",
 "CHECK",
 "CANCEL",
 "AGO",
 "LAST_SAVED",
 "SHARE",
 "COPIED_TO_CLIPBOARD",
 "SHARE_TEXT",
 "LEFT_MOUSE_CLICK",
 "PLACE_BRUSH",
 "RIGHT_MOUSE_CLICK",
 "PLACE_X",
 "MOUSE_DRAG",
 "PLACE_DRAG",
 "NUMBER_KEYS",
 "NUMBER_CONTROLS",
 "TAB",
 "NEXT_BRUSH",
 "SHIFT_TAB",
 "PREV_BRUSH",
 "ESC",
 "SETTINGS_CONTROL",
 "PLACE_WATER",
 "PLACE_NOWATER",
 "PLACE_BOAT",
 "PLACE_NOBOAT",
 "UNDO",
 "REDO",
 "TAP",
 "HOLD",
 "DRAG_TOUCH",
 "CONTROL_LIST",
 "PREVIEW",
 "MOUSE_HOVER",
 "LEADERBOARDS",
 "MISTAKE",
 "MISTAKES",
 "VSYNC",
 "DISABLED",
 "ENABLED",
 "ADAPTATIVE",
 "MAILBOX",
 "TUT_BOATS",
 "TUT_MOUSE1",
 "TUT_MOUSE2",
 "TUT_TOG_SEP",
 "TUT_UNKNOWN",
 "OPEN_WORKSHOP",
 "TODAY",
 "YESTERDAY",
 "SHOW_TIMER",
 "QUITTING",
 "ALLOW_MISTAKES",
 "PROGRESS_ON_UNKNOWN",
 "LESS_THREE_MISTAKES",
 "PREVIEW_TUT",
 "TUT_PREVIEW",
 "HOVER",
 "SHOW_BUBBLES",
 "EXTRA_LEVELS_BUTTON"
]