# Keys for LocalizationManger to use in source code: MIT License
# @author Vladimir Petrenko
@tool
class_name LocalizationKeys

const TEST = "TEST"
const YES = "YES"
const NO = "NO"
const EXIT_BUTTON = "EXIT_BUTTON"
const PLAY_BUTTON = "PLAY_BUTTON"
const LEVEL_EDITOR_BUTTON = "LEVEL_EDITOR_BUTTON"
const EXIT_CONFIRMATION = "EXIT_CONFIRMATION"
const DEFAULT_CONFIRMATION = "DEFAULT_CONFIRMATION"
const WATERS_COUNTER = "WATERS_COUNTER"
const BOATS_COUNTER = "BOATS_COUNTER"
const MISTAKES_COUNTER = "MISTAKES_COUNTER"
const MASTER_SOUND = "MASTER_SOUND"
const BGM_SOUND = "BGM_SOUND"
const SFX_SOUND = "SFX_SOUND"
const FULLSCREEN = "FULLSCREEN"
const SAVE_AND_EXIT = "SAVE_AND_EXIT"
const AQUARIUMS = "AQUARIUMS"
const SIZE = "SIZE"
const AMOUNT = "AMOUNT"
const BACK = "BACK"
const CONTINUE = "CONTINUE"
const CREATE_NEW_LEVEL = "CREATE_NEW_LEVEL"
const YOUR_LEVELS = "YOUR_LEVELS"
const PROFILE = "PROFILE"
const CHANGE_PROFILE = "CHANGE_PROFILE"
const CONFIRM_DELETE_PROFILE = "CONFIRM_DELETE_PROFILE"
const CONFIRM_RESET_LEVEL = "CONFIRM_RESET_LEVEL"
const LEVELS_COMPLETED = "LEVELS_COMPLETED"
const WORKSHOP_BUTTON = "WORKSHOP_BUTTON"
const WORKSHOP_LEVELS = "WORKSHOP_LEVELS"
const PLAY_LEVEL_TOOLTIP = "PLAY_LEVEL_TOOLTIP"
const EDIT_LEVEL_TOOLTIP = "EDIT_LEVEL_TOOLTIP"
const UPLOAD_LEVEL_TOOLTIP = "UPLOAD_LEVEL_TOOLTIP"
const DELETE_LEVEL_TOOLTIP = "DELETE_LEVEL_TOOLTIP"
const NOT_INSTALLED = "NOT_INSTALLED"
const RANDOM_BUTTON = "RANDOM_BUTTON"
const RANDOM_TITLE = "RANDOM_TITLE"
const EASY_BUTTON = "EASY_BUTTON"
const MEDIUM_BUTTON = "MEDIUM_BUTTON"
const HARD_BUTTON = "HARD_BUTTON"
const EXPERT_BUTTON = "EXPERT_BUTTON"
const INSANE_BUTTON = "INSANE_BUTTON"
const CONTINUE_RANDOM_BUTTON = "CONTINUE_RANDOM_BUTTON"
const RANDOM_COMPLETED = "RANDOM_COMPLETED"
const CONFIRM_NEW_RANDOM = "CONFIRM_NEW_RANDOM"
const UNIQUE_SOLUTION_DESCRIPTION = "UNIQUE_SOLUTION_DESCRIPTION"
const PLAYTEST = "PLAYTEST"
const LEVEL_DESCRIPTION_PLACEHOLDER = "LEVEL_DESCRIPTION_PLACEHOLDER"
const LEVEL_TITLE_PLACEHOLDER = "LEVEL_TITLE_PLACEHOLDER"
const EASY_TOOLTIP = "EASY_TOOLTIP"
const MEDIUM_TOOLTIP = "MEDIUM_TOOLTIP"
const MEDIUM_TOOLTIP_DISABLED = "MEDIUM_TOOLTIP_DISABLED"
const HARD_TOOLTIP = "HARD_TOOLTIP"
const HARD_TOOLTIP_DISABLED = "HARD_TOOLTIP_DISABLED"
const EXPERT_TOOLTIP = "EXPERT_TOOLTIP"
const EXPERT_TOOLTIP_DISABLED = "EXPERT_TOOLTIP_DISABLED"
const INSANE_TOOLTIP = "INSANE_TOOLTIP"
const INSANE_TOOLTIP_DISABLED = "INSANE_TOOLTIP_DISABLED"
const GENERATING_LEVEL = "GENERATING_LEVEL"
const LEVEL_01_01 = "LEVEL_01_01"
const LEVEL_01_02 = "LEVEL_01_02"
const LEVEL_01_03 = "LEVEL_01_03"
const LEVEL_01_04 = "LEVEL_01_04"
const LEVEL_01_05 = "LEVEL_01_05"
const LEVEL_01_06 = "LEVEL_01_06"
const LEVEL_01_07 = "LEVEL_01_07"
const LEVEL_01_08 = "LEVEL_01_08"
const LEVEL_02_01 = "LEVEL_02_01"
const LEVEL_02_02 = "LEVEL_02_02"
const LEVEL_02_03 = "LEVEL_02_03"
const LEVEL_02_04 = "LEVEL_02_04"
const LEVEL_02_05 = "LEVEL_02_05"
const LEVEL_02_06 = "LEVEL_02_06"
const LEVEL_02_07 = "LEVEL_02_07"
const LEVEL_02_08 = "LEVEL_02_08"
const LEVEL_03_01 = "LEVEL_03_01"
const LEVEL_03_02 = "LEVEL_03_02"
const LEVEL_03_03 = "LEVEL_03_03"
const LEVEL_03_04 = "LEVEL_03_04"
const LEVEL_03_05 = "LEVEL_03_05"
const LEVEL_03_06 = "LEVEL_03_06"
const LEVEL_03_07 = "LEVEL_03_07"
const LEVEL_03_08 = "LEVEL_03_08"
const LEVEL_04_01 = "LEVEL_04_01"
const LEVEL_04_02 = "LEVEL_04_02"
const LEVEL_04_03 = "LEVEL_04_03"
const LEVEL_04_04 = "LEVEL_04_04"
const LEVEL_04_05 = "LEVEL_04_05"
const LEVEL_04_06 = "LEVEL_04_06"
const LEVEL_04_07 = "LEVEL_04_07"
const LEVEL_04_08 = "LEVEL_04_08"
const LEVEL_05_01 = "LEVEL_05_01"
const LEVEL_05_02 = "LEVEL_05_02"
const LEVEL_05_03 = "LEVEL_05_03"
const LEVEL_05_04 = "LEVEL_05_04"
const LEVEL_05_05 = "LEVEL_05_05"
const LEVEL_05_06 = "LEVEL_05_06"
const LEVEL_05_07 = "LEVEL_05_07"
const LEVEL_05_08 = "LEVEL_05_08"
const LEVEL_06_01 = "LEVEL_06_01"
const LEVEL_06_02 = "LEVEL_06_02"
const LEVEL_06_03 = "LEVEL_06_03"
const LEVEL_06_04 = "LEVEL_06_04"
const LEVEL_06_05 = "LEVEL_06_05"
const LEVEL_06_06 = "LEVEL_06_06"
const LEVEL_06_07 = "LEVEL_06_07"
const LEVEL_06_08 = "LEVEL_06_08"
const DAILY_START = "DAILY_START"
const DAILY_CONTINUE = "DAILY_CONTINUE"
const DAILY_COMPLETED = "DAILY_COMPLETED"
const DAILY_TOOLTIP = "DAILY_TOOLTIP"
const HOURS_LEFT = "HOURS_LEFT"
const MINUTES_LEFT = "MINUTES_LEFT"
const MONDAY = "MONDAY"
const TUESDAY = "TUESDAY"
const WEDNESDAY = "WEDNESDAY"
const THURSDAY = "THURSDAY"
const FRIDAY = "FRIDAY"
const SATURDAY = "SATURDAY"
const SUNDAY = "SUNDAY"

const KEYS = [
 "TEST",
 "YES",
 "NO",
 "EXIT_BUTTON",
 "PLAY_BUTTON",
 "LEVEL_EDITOR_BUTTON",
 "EXIT_CONFIRMATION",
 "DEFAULT_CONFIRMATION",
 "WATERS_COUNTER",
 "BOATS_COUNTER",
 "MISTAKES_COUNTER",
 "MASTER_SOUND",
 "BGM_SOUND",
 "SFX_SOUND",
 "FULLSCREEN",
 "SAVE_AND_EXIT",
 "AQUARIUMS",
 "SIZE",
 "AMOUNT",
 "BACK",
 "CONTINUE",
 "CREATE_NEW_LEVEL",
 "YOUR_LEVELS",
 "PROFILE",
 "CHANGE_PROFILE",
 "CONFIRM_DELETE_PROFILE",
 "CONFIRM_RESET_LEVEL",
 "LEVELS_COMPLETED",
 "WORKSHOP_BUTTON",
 "WORKSHOP_LEVELS",
 "PLAY_LEVEL_TOOLTIP",
 "EDIT_LEVEL_TOOLTIP",
 "UPLOAD_LEVEL_TOOLTIP",
 "DELETE_LEVEL_TOOLTIP",
 "NOT_INSTALLED",
 "RANDOM_BUTTON",
 "RANDOM_TITLE",
 "EASY_BUTTON",
 "MEDIUM_BUTTON",
 "HARD_BUTTON",
 "EXPERT_BUTTON",
 "INSANE_BUTTON",
 "CONTINUE_RANDOM_BUTTON",
 "RANDOM_COMPLETED",
 "CONFIRM_NEW_RANDOM",
 "UNIQUE_SOLUTION_DESCRIPTION",
 "PLAYTEST",
 "LEVEL_DESCRIPTION_PLACEHOLDER",
 "LEVEL_TITLE_PLACEHOLDER",
 "EASY_TOOLTIP",
 "MEDIUM_TOOLTIP",
 "MEDIUM_TOOLTIP_DISABLED",
 "HARD_TOOLTIP",
 "HARD_TOOLTIP_DISABLED",
 "EXPERT_TOOLTIP",
 "EXPERT_TOOLTIP_DISABLED",
 "INSANE_TOOLTIP",
 "INSANE_TOOLTIP_DISABLED",
 "GENERATING_LEVEL",
 "LEVEL_01_01",
 "LEVEL_01_02",
 "LEVEL_01_03",
 "LEVEL_01_04",
 "LEVEL_01_05",
 "LEVEL_01_06",
 "LEVEL_01_07",
 "LEVEL_01_08",
 "LEVEL_02_01",
 "LEVEL_02_02",
 "LEVEL_02_03",
 "LEVEL_02_04",
 "LEVEL_02_05",
 "LEVEL_02_06",
 "LEVEL_02_07",
 "LEVEL_02_08",
 "LEVEL_03_01",
 "LEVEL_03_02",
 "LEVEL_03_03",
 "LEVEL_03_04",
 "LEVEL_03_05",
 "LEVEL_03_06",
 "LEVEL_03_07",
 "LEVEL_03_08",
 "LEVEL_04_01",
 "LEVEL_04_02",
 "LEVEL_04_03",
 "LEVEL_04_04",
 "LEVEL_04_05",
 "LEVEL_04_06",
 "LEVEL_04_07",
 "LEVEL_04_08",
 "LEVEL_05_01",
 "LEVEL_05_02",
 "LEVEL_05_03",
 "LEVEL_05_04",
 "LEVEL_05_05",
 "LEVEL_05_06",
 "LEVEL_05_07",
 "LEVEL_05_08",
 "LEVEL_06_01",
 "LEVEL_06_02",
 "LEVEL_06_03",
 "LEVEL_06_04",
 "LEVEL_06_05",
 "LEVEL_06_06",
 "LEVEL_06_07",
 "LEVEL_06_08",
 "DAILY_START",
 "DAILY_CONTINUE",
 "DAILY_COMPLETED",
 "DAILY_TOOLTIP",
 "HOURS_LEFT",
 "MINUTES_LEFT",
 "MONDAY",
 "TUESDAY",
 "WEDNESDAY",
 "THURSDAY",
 "FRIDAY",
 "SATURDAY",
 "SUNDAY"
]