import { RandomNumberGenerator } from "../model/RandomNumberGenerator";
import { consistent_hash } from "./RandomHub";

export const ADJECTIVES: string[] = [
  "Aquatic",
  "Oceanic",
  "Marine",
  "Watery",
  "Nautical",
  "Briny",
  "Submerged",
  "Deep-sea",
  "Seafaring",
  "Coastal",
  "Saline",
  "Abyssal",
  "Tidal",
  "Luminous",
  "Buoyant",
  "Wave-like",
  "Planktonic",
  "Eel-like",
  "Coraline",
  "Silvery",
  "Translucent",
  "Iridescent",
  "Murky",
  "Mysterious",
  "Swift",
  "Elusive",
  "Graceful",
  "Serene",
  "Playful",
  "Majestic",
  "Turquoise",
  "Sapphire",
  "Bubbling",
  "Sparkling",
  "Foamy",
  "Rippling",
  "Sleek",
  "Sprightly",
  "Salty",
  "Shimmering",
  "Whirlpool",
  "Zephyrous",
  "Glistening",
  "Azure",
  "Pelagic",
  "Benthic",
  "Labyrinthine",
  "Slippery",
  "Sculpted",
  "Twinkling",
  "Drifting",
  "Spectacular",
  "Gentle",
  "Crested",
  "Harmonious",
  "Resilient",
  "Whispering",
  "Exotic",
  "Endless",
  "Prismatic",
  "Sandy",
  "Exhilarating",
  "Delicate",
  "Radiant",
  "Whimsical",
  "Mystical",
  "Breathtaking",
  "Effervescent",
  "Fluid",
  "Enigmatic",
  "Lively",
  "Enchanting",
  "Infinite",
  "Soothing",
  "Reflective",
  "Dazzling",
  "Celestial",
  "Undulating",
  "Symbiotic",
  "Magnetic",
  "Mesmerizing",
  "Vibrant",
  "Undiscovered",
  "Turbulent",
  "Ethereal",
  "Melodic",
  "Ephemeral",
  "Eternal",
  "Tranquil",
  "Aqueous",
  "Vivid",
];

export const ANIMALS: string[] = [
  "fish",
  "shark",
  "dolphin",
  "whale",
  "seal",
  "octopus",
  "jellyfish",
  "crab",
  "lobster",
  "starfish",
  "sea turtle",
  "squid",
  "eel",
  "clownfish",
  "swordfish",
  "anemone",
  "manatee",
  "seahorse",
  "stingray",
  "penguin",
  "walrus",
  "sea otter",
  "cuttlefish",
  "manta ray",
  "sea lion",
  "moray eel",
  "bluefin tuna",
  "humpback whale",
  "barracuda",
  "sardine",
  "salmon",
  "tuna",
  "marlin",
  "angelfish",
  "pufferfish",
  "grouper",
  "clam",
  "krill",
  "orca",
  "beluga whale",
  "humphead wrasse",
  "hermit crab",
];

/**
 * Generates a deterministic aquatic display name from a seed string (e.g. PlayFabId)
 * matching Godot's NameGenerator.gd implementation exactly.
 */
export function getGeneratedName(seedStr: string): string {
  const rng = new RandomNumberGenerator();
  rng.set_seed(consistent_hash(seedStr));
  const adj = ADJECTIVES[rng.randi_range(0, ADJECTIVES.length - 1)];
  const animal = ANIMALS[rng.randi_range(0, ANIMALS.length - 1)];
  return `${adj} ${animal}`;
}
