
class_name NameGenerator

const ADJECTIVES: Array[String] = [
  "Aquatic",
  "Oceanic",
  "Marine",
  "Watery",
  "Nautical",
  "Briny",
  "Submerged",
  "Deep-sea",
  "Seafaring",
  "Coastal",
  "Saline",
  "Abyssal",
  "Tidal",
  "Luminous",
  "Buoyant",
  "Wave-like",
  "Planktonic",
  "Eel-like",
  "Coraline",
  "Silvery",
  "Translucent",
  "Iridescent",
  "Murky",
  "Mysterious",
  "Swift",
  "Elusive",
  "Graceful",
  "Serene",
  "Playful",
  "Majestic",
  "Turquoise",
  "Sapphire",
  "Bubbling",
  "Sparkling",
  "Foamy",
  "Rippling",
  "Sleek",
  "Sprightly",
  "Salty",
  "Shimmering",
  "Whirlpool",
  "Zephyrous",
  "Glistening",
  "Azure",
  "Pelagic",
  "Benthic",
  "Labyrinthine",
  "Slippery",
  "Sculpted",
  "Twinkling",
  "Drifting",
  "Spectacular",
  "Gentle",
  "Crested",
  "Harmonious",
  "Resilient",
  "Whispering",
  "Exotic",
  "Endless",
  "Prismatic",
  "Sandy",
  "Exhilarating",
  "Delicate",
  "Radiant",
  "Whimsical",
  "Mystical",
  "Breathtaking",
  "Effervescent",
  "Fluid",
  "Enigmatic",
  "Lively",
  "Enchanting",
  "Infinite",
  "Soothing",
  "Reflective",
  "Dazzling",
  "Celestial",
  "Undulating",
  "Symbiotic",
  "Magnetic",
  "Mesmerizing",
  "Vibrant",
  "Undiscovered",
  "Turbulent",
  "Ethereal",
  "Melodic",
  "Ephemeral",
  "Eternal",
  "Tranquil",
  "Aqueous",
  "Vivid",
]

const ANIMALS: Array[String] = [
  "fish",
  "shark",
  "dolphin",
  "whale",
  "seal",
  "octopus",
  "jellyfish",
  "crab",
  "lobster",
  "starfish",
  "sea turtle",
  "squid",
  "eel",
  "clownfish",
  "swordfish",
  "anemone",
  "manatee",
  "seahorse",
  "stingray",
  "penguin",
  "walrus",
  "sea otter",
  "cuttlefish",
  "manta ray",
  "sea lion",
  "moray eel",
  "bluefin tuna",
  "humpback whale",
  "barracuda",
  "sardine",
  "salmon",
  "tuna",
  "marlin",
  "angelfish",
  "pufferfish",
  "grouper",
  "clam",
  "krill",
  "orca",
  "beluga whale",
  "humphead wrasse",
  "hermit crab",
]

static func get_name(rng: RandomNumberGenerator, seed_: String) -> String:
	rng.seed = RandomHub.consistent_hash(seed_)
	return "%s %s" % [
		ADJECTIVES[rng.randi_range(0, ADJECTIVES.size() - 1)],
		ANIMALS[rng.randi_range(0, ANIMALS.size() - 1)],
	]
